### ISSUE TITLE
为什么在静态调用输出对象的时候不支持type呢?

### ISSUE THREAD

**Issue by lihaotian0607** [inhere/php-console#12]
show::info('111'); 的时候控制台会输出 [INFO] 1111

是不是在参数中增加一个type

看了下代码, 在魔术方法中 的type 直接获取了style 
```
 $style = self::$blockMethods[$method];
 return self::block($msg, $style === 'primary' ? 'IMPORTANT' : $style, $style, $quit);
```
目前项目中修改魔术方法中的参数获取,在使用静态调用的时候可以传递type,
想问下目前这样做的目的

**Comment by inhere** [comment]
> 想问下目前这样做的目的

几个魔术方法只是为几个常用的类型(info error warning 等)提功快速使用方法 😄 所以 `Show::info` type就是方法名称 `info`

> 在使用静态调用的时候可以传递type

需要自定义type 可以直接调用，魔术方法里使用的原始方法

```php
public static function block($messages, string $type = 'MESSAGE', string $style = Style::NORMAL, $quit = false): int

// example
Show::block('my message', 'MYTYPE', Style::WARNING);
```
