### ISSUE TITLE
call 'onAppStop' service, if it is registered.

### ISSUE THREAD

**Issue by hs-llsong** [inhere/php-console#13]
https://github.com/inhere/php-console/blob/2.x/src/Base/AbstractApplication.php#L212

```php
        // call 'onAppStop' service, if it is registered.
        $this->fire(self::ON_STOP_RUN, $this);
```

这里的 onAppStop service 怎么使用呢？

**Comment by inhere** [comment]
这里是个事件。注册了就可以用了。

```php
use Inhere\Console\Application;

$app = new Application()


$app->on(Application::ON_STOP_RUN, function () {
	echo 'cli app stopped';
});
```

**Comment by inhere** [comment]
这里是个事件。注册了就可以用了。

```php
use Inhere\Console\Application;

$app = new Application()


$app->on(Application::ON_STOP_RUN, function () {
	echo 'cli app stopped';
});
```

**Comment by hs-llsong** [comment]
谢谢哦 前辈 请问

`\Inhere\Console\Application` 在脚本异常退出时怎么才能执行一下正在运行的 `\Inhere\Console\Command` 的 `afterExecute()` 或者自定义的方法呢，因为当前正在运行的 `Command` 在异常退出时有一些数据需要处理才能退出。。。

**Comment by inhere** [comment]
`command` 里面执行出错

- 可以注册 `ON_RUN_ERROR` 事件：

https://github.com/inhere/php-console/blob/ba30f06c0ad3d26d9fc56debd6e46cc4a68adb81/src/Base/AbstractApplication.php#L176-L183

- command 里，你加上 try catch执行。:)

**Comment by hs-llsong** [comment]
`$this->fire(self::ON_RUN_ERROR, $e, $this); ` 的 `ON_RUN_ERROR` 怎么注册到 `Command` 类里面呢，因为那些变量和属性都在 `Command`  类里面

```
$app->on(Application::ON_RUN_ERROR, function () {
	(new namespace\MyCommand())->onRunError();
});
```

会报错：

```
[ERROR] An error occurred! MESSAGE: Too few arguments to function Inhere\Console\Base\AbstractCommand::__construct(), 0 passed in /Project/cli.php on line 61 and at least 2 expected
```

**Comment by inhere** [comment]
那你最好加上try catch 执行 command 里面的逻辑，这样就在同一个对象里了。

**Comment by hs-llsong** [comment]
明白子 多谢前辈指点哦
