### ISSUE TITLE
命令组支持能否更加完善

### ISSUE THREAD

**Issue by jdkysq** [inhere/php-console#19]
这个组件太好用了。
【添加命令组】这里能否对每个命令添加类似addDescription，子命令完全依靠文档注释虽然很好用，但是在实际上线时候我们会将所有注释全部去掉。

我们现在做一个phar打包的项目，我们希望在phar包里不要有注释存在。

**Comment by inhere** [comment]
每个子命令的选项、参数也可以通过代码里来定义，不使用注解：

> 说明：子命令 `defArg` 的命令方法为 `defArgCommand` 那它的配置方法就是 `{COMMAND}+Configure` 即 `defArgConfigure`

```php
class HomeController extends Controller
{
    protected static $name = 'home';

    protected static $description = 'This is a demo command controller. there are some command usage examples(2)';


    /**
     * command `defArgCommand` config
     * @throws LogicException
     */
    protected function defArgConfigure(): void
    {
        $this->createDefinition()
            ->setDescription('the command arg/opt config use defined configure, it like symfony console: argument define by position')
            ->addArgument('name', Input::ARG_REQUIRED, "description for the argument 'name'")
            ->addOption('yes', 'y', Input::OPT_BOOLEAN, "description for the option 'yes'")
            ->addOption('opt1', null, Input::OPT_REQUIRED, "description for the option 'opt1'");
    }

    /**
     * the command arg/opt config use defined configure, it like symfony console: argument define by position
     */
    public function defArgCommand(): void
    {
        $this->output->dump($this->input->getArgs(), $this->input->getOpts(), $this->input->getBoolOpt('y'));
    }
}
```

**Comment by jdkysq** [comment]
谢谢，看了文档没看例子

**Comment by jdkysq** [comment]
```
    public function defArgCommand(): void
    {
        $this->output->dump($this->input->getArgs(), $this->input->getOpts(), $this->input->getBoolOpt('y'));
    }
````

将上面的注释去掉依旧没办法使用`setDescription`，我多次尝试发现，只有在执行子方法的时候才会触发配置

**Comment by jdkysq** [comment]
> 每个子命令的选项，参数也可以通过代码里来定义，不使用注解：
> 
> > 说明：子命令`defArg`的命令方法为`defArgCommand`那它的配置方法就是`{COMMAND}+Configure`即`defArgConfigure`
> 
> ```
>  HomeController 类扩展 Controller
> {
>     受保护的 静态 $ name = 'home' ;
> 
>     protected  static  $ description = '这是一个演示命令控制器。有一些命令用法示例（2）'；
> 
> 
>     / ** 
>      *命令`defArgCommand` config 
>      * @throws LogicException 
>      * /
>     受保护的 函数 defArgConfigure（）：void
>     {
>         $本- > createDefinition（）
>             -> setDescription（'命令arg / opt config使用已定义的configure，就像symfony控制台：参数由位置定义'）
>             -> addArgument（'name'，输入:: ARG_REQUIRED，“参数'name'的描述”）
>             -> addOption（'yes'，'y'，Input :: OPT_BOOLEAN，“选项'yes'的描述”）
>             -> addOption（'opt1'，null，输入:: :: OPT_REQUIRED，“选项'opt1'的描述”）；
>     }
> 
>     / ** 
>      *命令arg / opt config使用定义的configure，就像symfony控制台：参数由位置定义
>      * /
>     公共 函数 defArgCommand（）：void
>     {
>         $这- >输出- >转储（ $这- >输入- > getArgs（）， $这- >输入- > getopts的（）， $这- >输入- > getBoolOpt（ 'Y' ））;
>     }
> }
> ```
> 
> 如上，可以给命令组里每个子命令添加配置信息（描述，参数，选项等）

```
    public function defArgCommand(): void
    {
        $this->output->dump($this->input->getArgs(), $this->input->getOpts(), $this->input->getBoolOpt('y'));
    }
````

将上面的注释去掉依旧没办法使用`setDescription`，我多次尝试发现，只有在执行子方法的时候才会触发配置

**Comment by inhere** [comment]
哦。。。 我看调整下

**Comment by inhere** [comment]
这个我已经调整了。需要在init时注册下子命令描述：

```php

    protected function init(): void
    {
        parent::init();

        $this->setCommandMeta('defArg', [
            'desc' => 'the command args and opts config use defined configure, it like symfony console, please see defArgConfigure()',
        ]);
    }
```

在 `defArgConfigure` 里就无需设置 `setDescription` 了，会自动从上面的配置获取

**Comment by jdkysq** [comment]
> 这个我已经调整了。需要在init时注册下子命令描述：
> 
> ```
>     protected function init(): void
>     {
>         parent::init();
> 
>         $this->setCommandMeta('defArg', [
>             'desc' => 'the command args and opts config use defined configure, it like symfony console, please see defArgConfigure()',
>         ]);
>     }
> ```
> 
> 在 `defArgConfigure` 里就无需设置 `setDescription` 了，会自动从上面的配置获取
> 
> ## 一次性配置多个：
> ```
> $this->commandMetas = [
> 	'command1' => [
>         'desc' => 'Description message',
>     ],
> 	'command2' => [
>         'desc' => 'Description message',
>     ],
> 	// ...
> ];
> ```

感谢作者的更新
