### ISSUE TITLE
兼容windows

### ISSUE THREAD

**Issue by gouchaoer** [inhere/php-console#2]
能在某种程度上兼容windows么？比如进度条，confirm之类的

**Comment by inhere** [comment]
windows 下的 cmd 还是 git-bash?

**Comment by gouchaoer** [comment]
cmd

**Comment by inhere** [comment]
默认都是支持的。 只是会自动去除 ANSI 颜色

**Comment by gouchaoer** [comment]
great
我就喜欢在win下跑东西，有了这个就能方便很多了，有一个功能想咨询一下，就是在win下假如一个任务在运行之中，我想让它退出，如果按ctrl+c的话就直接程序中断了，假所以我定义了按回车就告诉程序要退出了（我诚信每隔一点时间检测stdin是否有回车输入），但是win下从stdin读入字符是阻塞的，这个办法又只在linux下有效：。https://github.com/gouchaoer/Increment_Backup_To_Hive/blob/master/Increment_Backup_To_Hive.php#581有没有啥办法呢？

**Comment by gouchaoer** [comment]
我想找到一种信号告诉php脚本退出但是不强制退出，让脚本自己除了完了手里的事后自己退出

**Comment by inhere** [comment]
linux 下可以用 pcntl_* 来接受、处理信号，做相应处理
win 一般脚本一直是跑在前台(ctrl+c 就会中断), 就不好弄了

> 这种就该尽量在Linux 下跑啊 :)
