### ISSUE TITLE
请教下，如何关闭错误捕获呢？

### ISSUE THREAD

**Issue by linkimfly** [inhere/php-console#22]
### 如何关闭错误输出呢
> 有个老系统 接了php-console再用，有大量地方代码写的不是很严谨，属于警告类的错误，不是致命错误，例如未定义变量等等，如果要改代码量太大了，而且老系统改容易出问题，现在就是如果能够把错误关掉就能解决问题了。

**Comment by inhere** [comment]
在入口文件开头，配置下错误报告级别：

类似下面这样

```php
error_reporting(E_ERROR);

```

**Comment by linkimfly** [comment]
已解决，谢谢！其实一开始就这么设置了，但是没有作用。
