### ISSUE TITLE
会不会考虑动态表格

### ISSUE THREAD

**Issue by pakey** [inhere/php-console#5]
类似top htop命令 表格的内容可以定时动态刷新

**Comment by inhere** [comment]
你在程序里通过 `while` 定时渲染不能满足吗？ 能描述下什么样的场景里使用

**Comment by pakey** [comment]
一个任务列表 
展示每个任务执行状态 下次执行时间
当次执行的时候显示具体的进度

**Comment by inhere** [comment]
这个不也可以用 `while` 。每隔 1 秒，读取任务信息，然后用表格渲染

**Comment by pakey** [comment]
曾经自己写过一个
就是清屏这个没写好 导致内容错乱了
有什么好的处理办法么

**Comment by inhere** [comment]
`Inhere\Console\Components\Terminal` 提供了一些简单的屏幕和光标操作

> 不过只支持 Linux 或者 win下的 ConEmu 里

```php
// 清屏
Terminal::make()->screen(Terminal::CLEAR);
```

运行 `php examples/app home:cursor` 可以看到简单的效果
