### ISSUE TITLE
能否把类似进度条这样的动态更新能力单独开放出来

### ISSUE THREAD

**Issue by xpader** [inhere/php-console#7]
类似于：
$dynamic = Show::dynamicText('0%');
$dynamic->send('15%');
$dynamic->send(false); //结束

这样就可以不段更新刚刚输出的那个 0% 位置的文字的功能吗？

**Comment by inhere** [comment]
文本形式的进度显示吗？有这个方法呀 `Show::progressTxt()`

**Comment by inhere** [comment]
> Unix 下很多程序有一个旋转的小指示器，就是 [-], [\], [|], [/] 这几个杠交替的显示，就是希望能实现类似的功能。

这个已经有了 `Show::spinner`

> 至于文字变化的，你可以参照里面的 `Show::progressTxt()` 很简单的

**Comment by inhere** [comment]
已经添加了方法： `Show::dynamicText()`

使用示例可以运行 `php examples/app home:dynamicText` 查看效果，示例代码可以在对应的命令里看到
