### ISSUE TITLE
有什么方法可以拿到所有command，controller吗

### ISSUE THREAD

**Issue by hs-llsong** [inhere/php-console#8]
多谢大神写了这样一个神器，太好用了，赞！

主要想实现一次运行所有命令 `php app list all command` `php app run all command` 这样的快捷方法

**Comment by inhere** [comment]
包含每个controller的所有命令吗？

**Comment by hs-llsong** [comment]
如果可以，那就更牛逼了啊，我现在尝试继承 `extends Inhere\Console\Application` 给每一个运行起来的服务，加上 `start, stop, restart` 这样的维护命令，如果有很多 command/controller 一个一个的运行或者shell脚本写死都不够优雅嘛 ：D

**Comment by inhere** [comment]
你会运行很多命令进程作为服务？想统一管理(启动或停止)?

**Comment by hs-llsong** [comment]
是的是的，想直接拿到所有 command 然后 foreach 直接给全部运行了

**Comment by inhere** [comment]
😄 这种常住进程服务更适合使用 swoole, 使用原生容易出现问题 :)

**Comment by hs-llsong** [comment]
是的，我也想用 swoole 有推荐相关常驻进程文档示例之类的么，看 swoole_process 看的一头雾水

**Comment by inhere** [comment]
哈哈 swoole官网都是API式的文档，要用的话就得自己摸索下 
swoole 新出了进程池 [Process\Pool](https://wiki.swoole.com/wiki/page/p-process_pool.html) 听起来很符合你的场景

**Comment by inhere** [comment]
我看了下，现在已经提供了 `$app->getCommands()` `$app->getControllers()` 获取所有的command 和 controller
